### ISSUE TITLE
Architecture check fallback to basic-environment.txt if hardware.txt does not exist

### ISSUE THREAD

**Issue by Thr3d** [doccaz/scc-tools#11]
In some supportconfigs `hardware.txt` does not exist. Suggest adding a fallback file (`basic-environment.txt`) to check, or adding a flag to manually specify arch when running with `-d` against a supportconfig.

**Comment by doccaz** [comment]
Done! I now check for basic-environment.txt if hardware.txt does not exist. I also added a "-a" switch to override the architecture.
