### ISSUE TITLE
vercheck.py: Add option to specify directory to write CSV reports to

### ISSUE THREAD

**Issue by Thr3d** [doccaz/scc-tools#12]
By default vercheck.py writes CSV files to the current directory. Adding a flag to specify the output directory for these files would be helpful for creating automatic checks.

**Comment by doccaz** [comment]
Done! I also updated the known product list to include SP3/SP4 variants, as well as OpenSUSE Leap.

Just add the "-o <directory>" or "--outputdir <directory>" parameters before the "-d" option to specify the output directory for the CSV reports.
