### ISSUE TITLE
Implement a --version parameter

### ISSUE THREAD

**Issue by doccaz** [doccaz/scc-tools#24]
A colleague asked for adding a --version parameter. This is a bit tricky when dealing with GIT, unless I start using proper release tags and using git archive to do so. Even so, it seems things are a wee bit more complicated to have something like the old "$Id$" string in other version control systems.

**Comment by doccaz** [comment]
I really would like this to be automatic, and not use fixed strings anywhere (which I certainly will someday forget to update). Suggestions welcome.

**Comment by roseswe** [comment]
Please have a look at https://github.com/roseswe/gittag
I use this e.g. with https://github.com/cfg2html/cfg2html

**Comment by doccaz** [comment]
Closing this for now. I might add a proper pre-commit script later.
