### ISSUE TITLE
Please document the usage of vercheck-cache.py and fix "ModuleNotFoundError: No module named 'platformdirs'"

### ISSUE THREAD

**Issue by roseswe** [doccaz/scc-tools#25]
$ ./vercheck-cache.py 
Traceback (most recent call last):
  File "./vercheck-cache.py", line 6, in <module>
    from platformdirs import user_cache_dir
ModuleNotFoundError: No module named 'platformdirs'

**Comment by doccaz** [comment]
This looks suspiciously like VS Code trying to "fix" things automatically. I removed the import, and it's still working fine.
I really do not need the "platformdirs" module, I just happened to have a variable named  "user_cache_dir". 
Coincidentally the systems where we tested it must have had it installed previously, so I didn't notice it earlier.

**Comment by doccaz** [comment]
There you go, please try it again.
