### ISSUE TITLE
Bulk of messages

### ISSUE THREAD

**Issue by st-man** [doccaz/scc-tools#31]
When trying to analyze the supportconfig report dir (vercheck-nocache.py -d scc...) appear bulk of messages:
/vercheck-nocache.py:638: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.  return LooseVersion(v + '-' + r)
/vercheck-nocache.py:638: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.  return LooseVersion(v + '-' + r)
/vercheck-nocache.py:638: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.  return LooseVersion(v + '-' + r)
/vercheck-nocache.py:638: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.  return LooseVersion(v + '-' + r)
/vercheck-nocache.py:638: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.  return LooseVersion(v + '-' + r)
/vercheck-nocache.py:638: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.  return LooseVersion(v + '-' + r)
/vercheck-nocache.py:638: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.  return LooseVersion(v + '-' + r)
/vercheck-nocache.py:638: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.  return LooseVersion(v + '-' + r)
/vercheck-nocache.py:638: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.  return LooseVersion(v + '-' + r)
/vercheck-nocache.py:638: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.  return LooseVersion(v + '-' + r)
/vercheck-nocache.py:638: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.  return LooseVersion(v + '-' + r)

**Comment by doccaz** [comment]
Are you using the latest one? I did add  filter statement to avoid these warnings a couple of weeks ago.

**Comment by st-man** [comment]
-rw-r--r-- 1 user users  1071 Jan 11 20:41 LICENSE
-rw-r--r-- 1 user users  9614 Jan 11 20:41 README.md
-rwxr-xr-x 1 user users 87806 Jan 11 20:41 vercheck-cache.py
-rwxr-xr-x 1 user users 37244 Jan 11 20:41 vercheck-nocache.py
lrwxrwxrwx 1 user users    17 Jan 11 20:41 vercheck.py -> vercheck-cache.py
md5 is ef7f6f93c1fc2b3124f0bb5f40486285  vercheck-nocache.py

**Comment by doccaz** [comment]
Oh I see now. You're using the "-nocache" version. I'm no longer updating it, just the version with the cache, and the warning messages are disabled on it.

I've removed the older version and left only the supported one to avoid confusion.

**Comment by st-man** [comment]
Perfect solution. I'll check later when get another supportconfig file. Thanks
