### ISSUE TITLE
Option -a is undocumented

### ISSUE THREAD

**Issue by roseswe** [doccaz/scc-tools#32]
>> could not determine architecture for the supportconfig directory. Please supply one with -a.

maybe -a x86_64   ???

**Comment by doccaz** [comment]
It seems I added the exception treatment for missing/unknown architecture... but never added the parameter.

edit: I understood it wrong. The options IS already there and functional, just the help and documentation are omitting it.

**Comment by doccaz** [comment]
There you go,  I also updated all examples in the README.
