### ISSUE TITLE
Add the release date of package

### ISSUE THREAD

**Issue by rfparedes** [doccaz/scc-tools#6]
Seeing the release date of the package would be important to see at least for me.  For instance, I wanted to see if a new version of suse-migration-sle15-activation was released but while I see the version number, I then need to go into the SCC to find out the release date.

❯ vercheck.py -v -p 1755 -n suse-migration-sle15-activation
Using product ID 1755 (SUSE Linux Enterprise Server for SAP 12 SP4 x86_64)
looking for suse-migration-sle15-activation on product id 1755
version 1.2.0-6.8.1 is available on repository [Public Cloud Module 12 x86_64]
version 1.2.0-6.5.1 is available on repository [Public Cloud Module 12 x86_64]
version 1.2.0-6.11.3 is available on repository [Public Cloud Module 12 x86_64]
latest version for suse-migration-sle15-activation is 1.2.0-6.11.3

**Comment by doccaz** [comment]
Tested on ppc64le and on x86_64 supportconfigs, and it appears to be working fine.

**Comment by doccaz** [comment]
wrong issue! :1st_place_medal:

**Comment by doccaz** [comment]
Will need to study the SCC code and propose a change to the API. Working on that.

**Comment by doccaz** [comment]
Unfortunately this requires this field to be available in the API responses. I pinged the developers a while ago, but haven't heard from them since.
